"""Regression tests for P0: cross-function cache contamination.

Audit finding (Codex enterprise probe): two different @tokeymeter.cache-decorated
functions with the same model and the same prompt shared one default cache key,
so function B could return function A's cached answer without ever executing —
a correctness AND isolation defect (wrong answers across functions/tools/tenants).

Fix: the exact-cache key is namespaced by the decorated function's identity
(module+qualname) by default. Intentional cross-function sharing is opt-in via
an explicit `namespace=` or `shared_namespace=True`.

These tests pin BOTH the isolation default and the opt-in sharing paths so the
defect cannot silently return.
"""
import asyncio

import pytest

import tokeymeter
from tokeymeter.storage import MemoryStore


@pytest.fixture(autouse=True)
def _fresh_store():
    tokeymeter.set_default_store(MemoryStore())
    tokeymeter.reset()
    yield
    tokeymeter.reset()


def test_distinct_functions_do_not_share_cache_by_default():
    """The headline probe: B must NOT receive A's cached answer."""
    @tokeymeter.cache(model="gpt-4o")
    def func_a(prompt):
        return "ANSWER_FROM_A"

    @tokeymeter.cache(model="gpt-4o")
    def func_b(prompt):
        return "ANSWER_FROM_B"

    assert func_a("identical prompt") == "ANSWER_FROM_A"
    # Same prompt + same model + different function => must stay isolated.
    assert func_b("identical prompt") == "ANSWER_FROM_B"


def test_same_function_still_caches_itself():
    """Isolation must not break the actual feature: a function caches its own
    repeated calls."""
    calls = {"n": 0}

    @tokeymeter.cache(model="gpt-4o")
    def func(prompt):
        calls["n"] += 1
        return "value"

    func("p")
    func("p")
    assert calls["n"] == 1  # second call served from cache


def test_explicit_shared_namespace_enables_intentional_sharing():
    """Opt-in: functions that share an explicit namespace DO share cache."""
    @tokeymeter.cache(model="gpt-4o", namespace="shared-pool")
    def reader_a(prompt):
        return "FIRST_WRITER"

    @tokeymeter.cache(model="gpt-4o", namespace="shared-pool")
    def reader_b(prompt):
        return "SECOND_WRITER"

    assert reader_a("q") == "FIRST_WRITER"
    # Same explicit namespace => intentional sharing; B sees A's write.
    assert reader_b("q") == "FIRST_WRITER"


def test_shared_namespace_flag_restores_global_sharing():
    """shared_namespace=True reproduces global (un-namespaced) sharing for
    callers who explicitly want it."""
    @tokeymeter.cache(model="gpt-4o", shared_namespace=True)
    def g_a(prompt):
        return "GLOBAL_A"

    @tokeymeter.cache(model="gpt-4o", shared_namespace=True)
    def g_b(prompt):
        return "GLOBAL_B"

    assert g_a("shared") == "GLOBAL_A"
    assert g_b("shared") == "GLOBAL_A"  # shares the global keyspace


def test_isolation_holds_for_async_functions():
    """The same isolation must apply on the async path."""
    @tokeymeter.cache(model="gpt-4o")
    async def a_one(prompt):
        return "ASYNC_ONE"

    @tokeymeter.cache(model="gpt-4o")
    async def a_two(prompt):
        return "ASYNC_TWO"

    async def run():
        r1 = await a_one("same")
        r2 = await a_two("same")
        return r1, r2

    r1, r2 = asyncio.run(run())
    assert r1 == "ASYNC_ONE"
    assert r2 == "ASYNC_TWO"  # not contaminated by a_one


def test_namespace_and_lineage_compose():
    """Namespace (workload identity) and lineage (task boundary) are independent
    partitions and must compose without one defeating the other."""
    @tokeymeter.cache(model="gpt-4o")
    def worker(prompt):
        return "v"

    # Different lineages must not share even within the same function namespace.
    calls = {"n": 0}

    @tokeymeter.cache(model="gpt-4o")
    def counted(prompt):
        calls["n"] += 1
        return "out"

    with tokeymeter.lineage("task-1"):
        counted("p")
    with tokeymeter.lineage("task-2"):
        counted("p")  # different lineage => recompute despite same fn+prompt
    assert calls["n"] == 2


def test_dynamically_generated_functions_do_not_collide():
    """Functions generated by a factory share one __qualname__; they must still
    be isolated by default (no silent cross-function cache bleed)."""
    tokeymeter.set_default_store(MemoryStore())

    def make(tenant):
        @tokeymeter.cache(model="gpt-4o")
        def handler(prompt):
            return f"{tenant}:{prompt}"
        return handler

    a = make("tenantA")
    b = make("tenantB")
    assert a("q") == "tenantA:q"
    assert b("q") == "tenantB:q"   # must NOT receive tenantA's cached answer


def test_many_generated_functions_isolated_under_concurrency():
    """100 generated functions hammered concurrently with an identical prompt
    must each return only their own answer."""
    import concurrent.futures as cf
    tokeymeter.set_default_store(MemoryStore())

    fns = []
    for i in range(100):
        @tokeymeter.cache(model="gpt-4o")
        def fn(p, _i=i):
            return f"FN{_i}:{p}"
        fns.append((i, fn))

    errors = {"n": 0}

    def hammer(args):
        idx, fn = args
        for _ in range(20):
            if fn("identical") != f"FN{idx}:identical":
                errors["n"] += 1

    with cf.ThreadPoolExecutor(max_workers=32) as ex:
        list(ex.map(hammer, fns))
    assert errors["n"] == 0, f"cross-function bleed among generated functions: {errors['n']}"
