"""PUBLIC API SURFACE LOCK — freeze the contract.

These tests snapshot the public surface (exports + core signatures). Any
addition, removal, rename, or reorder breaks CI on purpose, so changing the
public API becomes a DELIBERATE, reviewed act — never a silent drift.

To intentionally change the API: update the frozen snapshot below in the same
commit, so the change is visible in the diff and code review.
"""
import inspect
import tokeymeter


# Frozen snapshot of the public API. Tokeymeter ships as the cost+proof wedge;
# action governance + compliance packs are carved to a later NOVUE product line.
FROZEN_EXPORTS = {
    'CacheOptimizer',
    'CacheReport',
    'CallableSummarizer',
    'Cascade',
    'CascadeResult',
    'CompressionResult',
    'Compressor',
    'Condition',
    'ConversationMemory',
    'DecisionRecord',
    'DefaultRedactor',
    'EndpointNotPermitted',
    'FernetCipher',
    'HaltEvent',
    'InMemoryMemoryStore',
    'KeyBudgetExceeded',
    'LLMLinguaCompressor',
    'MemoryStore',
    'ModelNotPermitted',
    'NoOpCipher',
    'PRIMARY_API',
    'PolicyViolation',
    'PrometheusCollector',
    'RedisStore',
    'RouteDecision',
    'Router',
    'Rule',
    'RulePolicyError',
    'RuleSet',
    'SQLiteMemoryStore',
    'SQLiteStore',
    'STARTER_POLICIES',
    'SafeCompressor',
    'SalienceCompressor',
    'SecurityPolicy',
    'SecurityPolicyError',
    'SemanticCache',
    'StructuralCompressor',
    'Summarizer',
    'TaskCallLimitExceeded',
    'TaskEnvelopeExceeded',
    'TaskLimitExceeded',
    'TaskLoopDetected',
    'TaskStalled',
    'TruncationSummarizer',
    'Turn',
    'VolatileFinding',
    'admin',
    'agent_report',
    'audit',
    'backends',
    'bind_task',
    'cache',
    'cache_stream',
    'capacity_reclaimed',
    'capacity_recovery_report',
    'capacity_report',
    'cascade',
    'chargeback_csv',
    'chargeback_report',
    'check_cache',
    'clear_cache',
    'clear_decision_subscribers',
    'clear_halt_handlers',
    'clear_keys',
    'clear_registered_pricing',
    'clear_rules',
    'close_packet',
    'compare_reports',
    'compose',
    'compress_tools',
    'compression',
    'compression_breaker_state',
    'compression_stats',
    'compression_verification_log',
    'compressor',
    'context_passport',
    'coverage_report',
    'current_agent',
    'current_data_class',
    'current_env',
    'current_region',
    'current_task_id',
    'data_class',
    'default_redactor',
    'derive_cluster_gpu_hour_rate',
    'derive_selfhost_rate',
    'doctor',
    'endpoint',
    'enterprise_defaults',
    'estimate_cost_with_source',
    'events',
    'flush_savings',
    'general_ledger_csv',
    'general_ledger_rows',
    'get_current_key',
    'get_endpoint',
    'get_principal',
    'get_rules',
    'get_security_policy',
    'get_task',
    'halt_handler_count',
    'hybrid_placement_csv',
    'hybrid_placement_report',
    'integrity',
    'is_vec_index_available',
    'key',
    'key_status',
    'leak_scan',
    'lineage',
    'list_starter_policies',
    'load_rules',
    'load_rules_file',
    'memory',
    'memory_fidelity_log',
    'meter',
    'metered_route',
    'metrics',
    'no_optimize',
    'on_decision',
    'on_halt',
    'optimize_cache',
    'plan_report',
    'policy_report',
    'pricing_info',
    'primary_api',
    'principal',
    'privacy',
    'prompt_ir',
    'redact',
    'region',
    'register_cluster_costs',
    'register_key',
    'register_pricing',
    'register_selfhost_pricing',
    'registered_pricing',
    'remove_decision_subscriber',
    'remove_halt_handler',
    'render_agents',
    'render_agents_html',
    'render_comparison',
    'render_plan',
    'render_suggestions',
    'report',
    'reset',
    'reset_compression_stats',
    'reset_savings',
    'reset_security_policy',
    'resolve_compliance',
    'router',
    'rules_version',
    'safe_compress',
    'savings_ledger_health',
    'savings_report',
    'scan_environment',
    'self_check',
    'semantic_available',
    'set_buffered_savings',
    'set_compression_max_reduction',
    'set_data_class',
    'set_default_redactor',
    'set_default_semantic_cache',
    'set_default_store',
    'set_endpoint',
    'set_env',
    'set_event_preview_policy',
    'set_fidelity_circuit_breaker',
    'set_home',
    'set_in_memory_savings',
    'set_principal',
    'set_queue_wait_ms',
    'set_region',
    'set_rules',
    'set_runtime_guards',
    'set_savings_path',
    'set_security_policy',
    'set_task',
    'simulate_rules',
    'starter_policy',
    'suggest_thresholds',
    'task',
    'task_snapshot',
    'tenant_scope',
    'unregister_key',
    'unregister_pricing',
    'unwrap',
    'verify_self',
    'warmup',
    'with_memory',
    'wrap',
    'wrap_langchain_llm',
    'wrap_llamaindex_llm',
    'write_agents_html',
}

# Core decorator signatures (positional/keyword parameter NAMES & ORDER).
FROZEN_CACHE_PARAMS = [
    'fn',
    'model',
    'store',
    'key_fn',
    'extract_text',
    'enabled',
    'semantic',
    'semantic_cache',
    'semantic_threshold',
    'prompt_arg',
    'ttl',
    'single_flight',
    'shadow',
    'redactor',
    'redact_response',
    'tag',
    'compressor',
    'verify_rate',
    'verify_similarity_fn',
    'high_stakes',
    'lineage',
    'namespace',
    'shared_namespace',
    'tenant',
    'endpoint',
    'extract_response_text',
]
FROZEN_CACHE_STREAM_PARAMS = [
    'fn',
    'model',
    'store',
    'key_fn',
    'extract_text',
    'enabled',
    'semantic',
    'semantic_cache',
    'semantic_threshold',
    'prompt_arg',
    'ttl',
    'shadow',
    'redactor',
    'redact_response',
    'tag',
    'compressor',
    'high_stakes',
    'lineage',
    'namespace',
    'shared_namespace',
    'tenant',
    'endpoint',
    'extract_response_text',
]


def test_public_exports_are_frozen():
    current = set(tokeymeter.__all__)
    added = current - FROZEN_EXPORTS
    removed = FROZEN_EXPORTS - current
    assert not added, f"NEW public exports (update the frozen snapshot deliberately): {sorted(added)}"
    assert not removed, f"REMOVED public exports (a breaking change!): {sorted(removed)}"


def test_all_exports_actually_exist():
    for name in tokeymeter.__all__:
        assert hasattr(tokeymeter, name), f"__all__ lists {name!r} but it is not importable"


def test_cache_signature_is_frozen():
    params = list(inspect.signature(tokeymeter.cache).parameters)
    assert params == FROZEN_CACHE_PARAMS, (
        "tokeymeter.cache signature changed. If intentional, update FROZEN_CACHE_PARAMS "
        f"in the same commit. Got: {params}")


def test_cache_stream_signature_is_frozen():
    params = list(inspect.signature(tokeymeter.cache_stream).parameters)
    assert params == FROZEN_CACHE_STREAM_PARAMS, (
        "tokeymeter.cache_stream signature changed. If intentional, update the snapshot. "
        f"Got: {params}")


def test_quality_preservation_surface_present():
    # The features that must remain public for the guarantees to be usable.
    for name in ("no_optimize", "lineage", "set_compression_max_reduction",
                 "set_fidelity_circuit_breaker", "compression_breaker_state",
                 "set_event_preview_policy", "set_runtime_guards", "prompt_ir"):
        assert name in tokeymeter.__all__ and hasattr(tokeymeter, name)
